version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000 #ext:int
    volumes:
      - .:/Users/macbook/Desktop/docker/xendit-1
    command: air cmd/main.go -b 0.0.0.0
    networks:
      - learning

  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/Users/macbook/Desktop/docker/xendit-1/lib/postgresql/data
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge

volumes:
  postgres-db: